name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov

      - name: Lint with flake8
        run: flake8 .

      # Run tests without coverage on push events
      - name: Run tests (push)
        if: github.event_name == 'push'
        run: pytest

      # Run tests with coverage check on pull request events
      - name: Run tests with coverage (PR)
        if: github.event_name == 'pull_request'
        run: pytest --cov=. --cov-fail-under=80 --cov-report=xml
